server:
  port: 8004


eureka:
  instance:
    instance-id: open-feign-consumer
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: feigen-consumer

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 3000

logging:
  level:
    com.dajiao.service: debug