server:
  port: 8010
spring:
  rabbitmq:
    port: 5672
    host: localhost
    password: guest
    username: guest
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dajiao918/springcloud_config.git
          search-paths:
            springcloud_config
      label: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"