server:
  port: 8009

eureka:
  instance:
    instance-id: gateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment_route1
#          uri: http://localhost:8001/
          uri: lb://PAYMENT
          predicates:
            - Path=/user/**
