server:
  port: 80

spring:
  application:
    name: consumer
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/book2?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: qwer
      driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka