server:
  port: 8006

eureka:
  instance:
    instance-id: hystrix-feign-consumer
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: hystrix-consumer

feign:
  hystrix:
    enabled: true